# Dependencies
markdown: kramdown
highlighter: rouge

kramdown:
    input: GFM
    syntax_highlighter: rouge

gems: [jekyll-sitemap, jekyll-seo-tag]

exclude: [vendor]

# Permalinks
permalink: /:title/

# Site
title: 'Study Weekly Brief'
description: 'A study weekly newsletter about myself'
url: https://weeklyarchiv.github.io
logo: /img/logo.png
timezone: America/Los_Angeles

twitter:
    username: dleyanlin

curator:
    name: 'drewz lin'
    url: https://twitter.com/dleyanlin

# Setup
excerpt_separator: <!--excerpt-->

# Data
links:
    rss: '/feed.xml'
    twitter: 'https://twitter.com/dleyanlin'
    github: 'https://github.com/weeklyarchive/weeklyarchive.github.io'
    issue: 'https://github.com/weeklyarchive/weeklyarchive.github.io/issues/new'
    pull: 'https://github.com/weeklyarchive/weeklyarchive.github.io/compare'
    #applenews: 'https://apple.news/TIlGIYluMTGWA-CIToVtF4Q'
